var Rapfi = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;h.expectedDataFileDownloads??(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;(function(c){function d(l,q,v,B){b?require("fs").readFile(l,(t,r)=>{t?B(t):v(r.buffer)}):(h.dataFileDownloads??(h.dataFileDownloads={}),fetch(l).catch(t=>Promise.reject(Error(`Network Error: ${l}`,{cause:t}))).then(t=>{if(!t.ok)return Promise.reject(Error(`${t.status}: ${t.url}`));
if(!t.body&&t.arrayBuffer)return t.arrayBuffer().then(v);const r=t.body.getReader(),A=()=>r.read().then(G).catch(O=>Promise.reject(Error(`Unexpected error while handling : ${t.url} ${O}`,{cause:O}))),D=[],K=Number(t.headers.get("Content-Length")??q);let ua=0;const G=({done:O,value:pb})=>{if(O){var ja=new Uint8Array(D.map(Qa=>Qa.length).reduce((Qa,cc)=>Qa+cc,0));O=0;for(var ka of D)ja.set(ka,O),O+=ka.length;v(ja.buffer)}else{D.push(pb);ua+=pb.length;h.dataFileDownloads[l]={loaded:ua,total:K};O=ka=
0;for(ja of Object.values(h.dataFileDownloads))ka+=ja.loaded,O+=ja.total;h.setStatus?.(`Downloading data... (${ka}/${O})`);return A()}};h.setStatus?.("Downloading data...");return A()}))}function e(l){console.error("package error:",l)}function f(l){function q(r,A,D){this.start=r;this.end=A;this.audio=D}function v(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;r=new Uint8Array(r);q.prototype.Wa=r;
r=c.files;for(var A=0;A<r.length;++A)q.prototype.La[r[A].filename].onload();l.removeRunDependency("datafile_rapfi-single.data")}q.prototype={La:{},open:function(r,A){this.name=A;this.La[A]=this;l.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.Va(this.Wa.subarray(this.start,this.end))},Va:function(r){l.FS_createDataFile(this.name,null,r,!0,!0,!0);l.removeRunDependency(`fp ${this.name}`);this.La[this.name]=null}};for(var B=c.files,t=0;t<B.length;++t)(new q(B[t].start,
B[t].end,B[t].audio||0)).open("GET",B[t].filename);l.addRunDependency("datafile_rapfi-single.data");l.preloadResults??(l.preloadResults={});l.preloadResults["rapfi-single.data"]={Fb:!1};n?(v(n),n=null):p=v}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+
"/");var g=h.locateFile?h.locateFile("rapfi-single.data",""):"rapfi-single.data",k=c.remote_package_size,p=null,n=h.getPreloadedPackage?h.getPreloadedPackage(g,k):null;n||d(g,k,l=>{p?(p(l),p=null):n=l},e);h.calledRun?f(h):(h.preRun??(h.preRun=[])).push(f)})({files:[{filename:"/classical210901.toml",start:0,end:5735},{filename:"/classical220723.toml",start:5735,end:11470},{filename:"/config.toml",start:11470,end:18183},{filename:"/mix9svqfreestyle_bsmix.bin.lz4",start:18183,end:10048581},
{filename:"/mix9svqrenju_bs15_black.bin.lz4",start:10048581,end:20032753},{filename:"/mix9svqrenju_bs15_white.bin.lz4",start:20032753,end:29877697},{filename:"/mix9svqstandard_bs15.bin.lz4",start:29877697,end:40223472},{filename:"/model210901.bin",start:40223472,end:40246676},{filename:"/model220723.bin",start:40246676,end:40306406}],remote_package_size:40306406})}})();h.sendCommand=h.sendCommand||null;h.terminate=h.terminate||null;h.onReceiveStdout=h.onReceiveStdout||(a=>console.log(a));
h.onReceiveStderr=h.onReceiveStderr||(a=>console.error(a));h.onExit=h.onExit||(a=>console.log("exited with code "+a));h.noExitRuntime=!0;h.preRun||(h.preRun=[]);
h.preRun.push(function(){let a=[];var b="",c=0;let d="",e="";const f=h.onReceiveStdout,g=h.onReceiveStderr;ha(function(){return c<b.length?b.charCodeAt(c++):0<a.length?(b=a.shift(),c=0,b.charCodeAt(c++)):null},function(p){p&&10!=p?d+=String.fromCharCode(p):(f(d),d="")},function(p){p&&10!=p?e+=String.fromCharCode(p):(g(e),e="")});const k=h.cwrap("gomocupLoopOnce","number",[]);h.sendCommand=function(p){a.push(p+"\n");k()};h.terminate=function(){h._emscripten_force_exit(0)}});
var ia=[],la="./this.program",ma=(a,b)=>{throw b;};"undefined"!=typeof __filename?_scriptName=__filename:ea&&(_scriptName=self.location.href);var na="",oa,pa;
if(fa){var fs=require("fs");require("path");na=__dirname+"/";pa=a=>{a=qa(a)?new URL(a):a;return fs.readFileSync(a)};oa=async a=>{a=qa(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(la=process.argv[1].replace(/\\/g,"/"));ia=process.argv.slice(2);ma=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea){try{na=(new URL(".",_scriptName)).href}catch{}ea&&(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
oa=async a=>{if(qa(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ra=console.log.bind(console),m=console.error.bind(console),sa,ta,va=!1,wa,u,w,xa,x,y,z,ya=!1,qa=a=>a.startsWith("file://");
function za(){var a=ta.buffer;u=new Int8Array(a);xa=new Int16Array(a);w=new Uint8Array(a);new Uint16Array(a);x=new Int32Array(a);y=new Uint32Array(a);new Float32Array(a);new Float64Array(a);z=new BigInt64Array(a);new BigUint64Array(a)}var C=0,Aa=null;function Ba(){C++;h.monitorRunDependencies?.(C)}function Ca(){C--;h.monitorRunDependencies?.(C);if(0==C&&Aa){var a=Aa;Aa=null;a()}}
function Da(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);va=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ea;async function Fa(a){if(!sa)try{var b=await oa(a);return new Uint8Array(b)}catch{}if(a==Ea&&sa)a=new Uint8Array(sa);else if(pa)a=pa(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ga(a,b){try{var c=await Fa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),Da(d)}}async function Ha(a){var b=Ea;if(!sa&&"function"==typeof WebAssembly.instantiateStreaming&&!qa(b)&&!fa)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return Ga(b,a)}
class Ia{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ja=a=>{for(;0<a.length;)a.shift()(h)},Ka=[],La=[],Ma=()=>{var a=h.preRun.shift();La.push(a)},Na=!1,Oa=[],Pa=0,E=0;function Ra(a,b,c){y[a.Ma+16>>2]=0;y[a.Ma+4>>2]=b;y[a.Ma+8>>2]=c}class Sa{constructor(a){this.ib=a;this.Ma=a-24}}
var Va=a=>{var b=E;if(!b)return Ta(0),0;var c=new Sa(b);y[c.Ma+16>>2]=b;var d=y[c.Ma+4>>2];if(!d)return Ta(0),b;for(var e of a){if(0===e||e===d)break;if(Ua(e,d,c.Ma+16))return Ta(e),b}Ta(d);return b},F=()=>{var a=x[+Wa>>2];Wa+=4;return a},Xa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ya=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Xa(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Za=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b=b&&b.slice(0,-1);return a+b},$a=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],ab=()=>{if(fa){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},bb=a=>{(bb=ab())(a)},cb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Xa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},db=(a,b)=>{function c(g){for(var k=0;k<g.length&&""===g[k];k++);for(var p=g.length-1;0<=p&&""===g[p];p--);return k>p?[]:g.slice(k,p-k+1)}a=cb(a).slice(1);b=cb(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},eb="undefined"!=
typeof TextDecoder?new TextDecoder:void 0,H=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&eb)return eb.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},fb=[],gb=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},I=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=
128|g&63}}b[c]=0;return c-e},hb=a=>{var b=Array(gb(a)+1);a=I(a,b,0,b.length);b.length=a;return b},ib=[];function jb(a,b){ib[a]={input:[],output:[],Sa:b};kb(a,lb)}
var lb={open(a){var b=ib[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close(a){a.tty.Sa.fsync(a.tty)},fsync(a){a.tty.Sa.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Sa.jb)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Sa.jb(a.tty)}catch(k){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Sa.bb)throw new J(60);try{for(var e=0;e<d;e++)a.tty.Sa.bb(a.tty,b[c+e])}catch(f){throw new J(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},mb={jb(){a:{if(!fb.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}fb=hb(a)}a=fb.shift()}return a},bb(a,b){null===b||10===b?(ra(H(a.output)),a.output=[]):0!=
b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ra(H(a.output)),a.output=[])},pb(){return{Ab:25856,Cb:5,zb:191,Bb:35387,yb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},qb(){return 0},rb(){return[24,80]}},nb={bb(a,b){null===b||10===b?(m(H(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(m(H(a.output)),a.output=[])}},L={Pa:null,Na(){return L.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);
L.Pa||(L.Pa={dir:{node:{Ra:L.Ha.Ra,Qa:L.Ha.Qa,lookup:L.Ha.lookup,Ya:L.Ha.Ya,rename:L.Ha.rename,unlink:L.Ha.unlink,rmdir:L.Ha.rmdir,readdir:L.Ha.readdir,symlink:L.Ha.symlink},stream:{Oa:L.Ia.Oa}},file:{node:{Ra:L.Ha.Ra,Qa:L.Ha.Qa},stream:{Oa:L.Ia.Oa,read:L.Ia.read,write:L.Ia.write,ab:L.Ia.ab,mb:L.Ia.mb}},link:{node:{Ra:L.Ha.Ra,Qa:L.Ha.Qa,readlink:L.Ha.readlink},stream:{}},gb:{node:{Ra:L.Ha.Ra,Qa:L.Ha.Qa},stream:ob}});c=qb(a,b,c,d);M(c.mode)?(c.Ha=L.Pa.dir.node,c.Ia=L.Pa.dir.stream,c.Ga={}):32768===
(c.mode&61440)?(c.Ha=L.Pa.file.node,c.Ia=L.Pa.file.stream,c.Ja=0,c.Ga=null):40960===(c.mode&61440)?(c.Ha=L.Pa.link.node,c.Ia=L.Pa.link.stream):8192===(c.mode&61440)&&(c.Ha=L.Pa.gb.node,c.Ia=L.Pa.gb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Ga[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Gb(a){return a.Ga?a.Ga.subarray?a.Ga.subarray(0,a.Ja):new Uint8Array(a.Ga):new Uint8Array(0)},Ha:{Ra(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=
a.rdev;M(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ja:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Qa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Ja!=b&&(0==b?(a.Ga=null,a.Ja=0):(c=a.Ga,a.Ga=new Uint8Array(b),c&&a.Ga.set(c.subarray(0,Math.min(b,a.Ja))),a.Ja=b)))},lookup(){throw L.hb;
},Ya(a,b,c,d){return L.createNode(a,b,c,d)},rename(a,b,c){try{var d=N(b,c)}catch(f){}if(d){if(M(a.mode))for(var e in d.Ga)throw new J(55);rb(d)}delete a.parent.Ga[a.name];b.Ga[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Ga[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=N(a,b),d;for(d in c.Ga)throw new J(55);delete a.Ga[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Ga)]},symlink(a,b,c){a=L.createNode(a,b,41471,0);a.link=
c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},Ia:{read(a,b,c,d,e){var f=a.node.Ga;if(e>=a.node.Ja)return 0;a=Math.min(a.node.Ja-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===u.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Ga||a.Ga.subarray)){if(f)return a.Ga=b.subarray(c,c+d),a.Ja=d;if(0===a.Ja&&0===e)return a.Ga=b.slice(c,c+d),a.Ja=d;if(e+d<=a.Ja)return a.Ga.set(b.subarray(c,
c+d),e),d}f=e+d;var g=a.Ga?a.Ga.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Ga,a.Ga=new Uint8Array(f),0<a.Ja&&a.Ga.set(g.subarray(0,a.Ja),0));if(a.Ga.subarray&&b.subarray)a.Ga.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ga[e+f]=b[c+f];a.Ja=Math.max(a.Ja,e+d);return d},Oa(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ja);if(0>b)throw new J(28);return b},ab(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.Ga;
if(e&2||!a||a.buffer!==u.buffer){d=!0;Da();e=void 0;if(!e)throw new J(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e)}}else d=!1,e=a.byteOffset;return{Ma:e,xb:d}},mb(a,b,c,d){L.Ia.write(a,b,0,d,c,!1);return 0}}},sb=async a=>{a=await oa(a);return new Uint8Array(a)},tb=[],ub=(a,b,c,d)=>{"undefined"!=typeof Browser&&Ra(Browser);var e=!1;tb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},vb=(a,b)=>{var c=0;a&&(c|=365);
b&&(c|=146);return c},wb=null,xb={},yb=[],zb=1,P=null,Ab=!1,Bb=!0,Cb={},J=class{name="ErrnoError";constructor(a){this.Ka=a}},Db=class{La={};node=null;get flags(){return this.La.flags}set flags(a){this.La.flags=a}get position(){return this.La.position}set position(a){this.La.position=a}},Eb=class{Ha={};Ia={};Ta=null;constructor(a,b,c,d){a=a||this;this.parent=a;this.Na=a.Na;this.id=zb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&
365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get tb(){return M(this.mode)}get sb(){return 8192===(this.mode&61440)}};
function Q(a,b={}){if(!a)throw new J(44);b.Za??(b.Za=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=wb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Za(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=Ya(e+"/"+a[f]);try{d=N(d,a[f])}catch(k){if(44===k?.Ka&&g&&b.vb)return{path:e};throw k;}!d.Ta||g&&!b.Za||(d=d.Ta.root);if(40960===(d.mode&61440)&&(!g||b.Xa)){if(!d.Ha.readlink)throw new J(52);
d=d.Ha.readlink(d);"/"===d.charAt(0)||(d=Za(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new J(32);}function Fb(a){for(var b;;){if(a===a.parent)return a=a.Na.lb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.length}function Hb(a){var b=Gb(a.parent.id,a.name);a.Ua=P[b];P[b]=a}
function rb(a){var b=Gb(a.parent.id,a.name);if(P[b]===a)P[b]=a.Ua;else for(b=P[b];b;){if(b.Ua===a){b.Ua=a.Ua;break}b=b.Ua}}function N(a,b){var c=M(a.mode)?(c=Ib(a,"x"))?c:a.Ha.lookup?0:2:54;if(c)throw new J(c);for(c=P[Gb(a.id,b)];c;c=c.Ua){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ha.lookup(a,b)}function qb(a,b,c,d){a=new Eb(a,b,c,d);Hb(a);return a}function M(a){return 16384===(a&61440)}function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Ib(a,b){if(Bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Kb(a,b){if(!M(a.mode))return 54;try{return N(a,b),20}catch(c){}return Ib(a,"wx")}function Lb(a,b,c){try{var d=N(a,b)}catch(e){return e.Ka}if(a=Ib(a,"wx"))return a;if(c){if(!M(d.mode))return 54;if(d===d.parent||"/"===Fb(d))return 10}else if(M(d.mode))return 31;return 0}function Mb(a){if(!a)throw new J(63);return a}
function R(a){a=yb[a];if(!a)throw new J(8);return a}function Nb(a,b=-1){a=Object.assign(new Db,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!yb[b])break a;throw new J(33);}a.fd=b;return yb[b]=a}function Ob(a,b=-1){a=Nb(a,b);a.Ia?.Eb?.(a);return a}function Pb(a,b){var c=null?.Ia.Qa,d=c?null:a;c=c??a.Ha.Qa;Mb(c);c(d,b)}var ob={open(a){a.Ia=xb[a.node.rdev].Ia;a.Ia.open?.(a)},Oa(){throw new J(70);}};function kb(a,b){xb[a]={Ia:b}}
function Qb(a,b){var c="/"===b;if(c&&wb)throw new J(10);if(!c&&b){var d=Q(b,{Za:!1});b=d.path;d=d.node;if(d.Ta)throw new J(10);if(!M(d.mode))throw new J(54);}b={type:a,Hb:{},lb:b,ub:[]};a=a.Na(b);a.Na=b;b.root=a;c?wb=a:d&&(d.Ta=b,d.Na&&d.Na.ub.push(b))}function Rb(a,b,c){var d=Q(a,{parent:!0}).node;a=$a(a);if(!a)throw new J(28);if("."===a||".."===a)throw new J(20);var e=Kb(d,a);if(e)throw new J(e);if(!d.Ha.Ya)throw new J(63);return d.Ha.Ya(d,a,b,c)}
function Sb(a,b=438){return Rb(a,b&4095|32768,0)}function S(a){return Rb(a,16895,0)}function Tb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Rb(a,b|8192,c)}function Ub(a,b){if(!cb(a))throw new J(44);var c=Q(b,{parent:!0}).node;if(!c)throw new J(44);b=$a(b);var d=Kb(c,b);if(d)throw new J(d);if(!c.Ha.symlink)throw new J(63);c.Ha.symlink(c,b,a)}
function Vb(a){var b=Q(a,{parent:!0}).node;a=$a(a);var c=N(b,a),d=Lb(b,a,!0);if(d)throw new J(d);if(!b.Ha.rmdir)throw new J(63);if(c.Ta)throw new J(10);b.Ha.rmdir(b,a);rb(c)}function Wb(a){var b=Q(a,{parent:!0}).node;if(!b)throw new J(44);a=$a(a);var c=N(b,a),d=Lb(b,a,!1);if(d)throw new J(d);if(!b.Ha.unlink)throw new J(63);if(c.Ta)throw new J(10);b.Ha.unlink(b,a);rb(c)}function Xb(a,b){a="string"==typeof a?Q(a,{Xa:!0}).node:a;Pb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Db:void 0})}
function Yb(a,b,c=438){if(""===a)throw new J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=Q(a,{Xa:!(b&131072),vb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new J(20);}else{if(e)throw new J(31);d=Rb(a,c|511,0);f=!0}if(!d)throw new J(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!M(d.mode))throw new J(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:M(d.mode)&&("r"!==Jb(b)||b&576)?31:Ib(d,Jb(b)):44))throw new J(e);if(b&512&&!f){e=d;e="string"==typeof e?Q(e,{Xa:!0}).node:e;if(M(e.mode))throw new J(31);if(32768!==(e.mode&61440))throw new J(28);var g=Ib(e,"w");if(g)throw new J(g);Pb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Nb({node:d,path:Fb(d),flags:b,seekable:!0,position:0,Ia:d.Ia,wb:[],error:!1});e.Ia.open&&e.Ia.open(e);f&&Xb(d,c&511);!h.logReadFiles||b&1||a in Cb||(Cb[a]=1);return e}
function Zb(a){if(null===a.fd)throw new J(8);a.$a&&(a.$a=null);try{a.Ia.close&&a.Ia.close(a)}catch(b){throw b;}finally{yb[a.fd]=null}a.fd=null}function $b(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.Ia.Oa)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.Ia.Oa(a,b,c);a.wb=[]}
function ac(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(M(a.node.mode))throw new J(31);if(!a.Ia.write)throw new J(28);a.seekable&&a.flags&1024&&$b(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.Ia.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function ha(a,b,c){Ab=!0;a=a??h.stdin;b=b??h.stdout;c=c??h.stderr;a?T("/dev","stdin",a):Ub("/dev/tty","/dev/stdin");b?T("/dev","stdout",null,b):Ub("/dev/tty","/dev/stdout");c?T("/dev","stderr",null,c):Ub("/dev/tty1","/dev/stderr");Yb("/dev/stdin",0);Yb("/dev/stdout",1);Yb("/dev/stderr",1)}function bc(a,b){a="string"==typeof a?a:Fb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ya(a+"/"+c);try{S(d)}catch(e){if(20!=e.Ka)throw e;}a=d}}return d}
function dc(a,b,c,d){a=Ya(("string"==typeof a?a:Fb(a))+"/"+b);return Sb(a,vb(c,d))}function ec(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Fb(a),g=b?Ya(a+"/"+b):a);a=vb(d,e);g=Sb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Xb(g,a|146);b=Yb(g,577);ac(b,c,0,c.length,0,f);Zb(b);Xb(g,a)}}
function T(a,b,c,d){a=Ya(("string"==typeof a?a:Fb(a))+"/"+b);b=vb(!!c,!!d);T.kb??(T.kb=64);var e=T.kb++<<8|0;kb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,p){for(var n=0,l=0;l<p;l++){try{var q=c()}catch(v){throw new J(29);}if(void 0===q&&0===n)throw new J(6);if(null===q||void 0===q)break;n++;g[k+l]=q}n&&(f.node.atime=Date.now());return n},write(f,g,k,p){for(var n=0;n<p;n++)try{d(g[k+n])}catch(l){throw new J(29);}p&&(f.node.mtime=f.node.ctime=Date.now());return n}});return Tb(a,
b,e)}function fc(a){if(!(a.sb||a.tb||a.link||a.Ga)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Ga=pa(a.url),a.Ja=a.Ga.length}catch(b){throw new J(29);}}}
function gc(a,b,c,d,e){class f{Wa=!1;La=[];Va=void 0;eb=0;cb=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.Va(l/this.chunkSize|0)[q]}}nb(l){this.Va=l}fb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),v,B=(v=l.getResponseHeader("Accept-Ranges"))&&"bytes"===v;l=(v=l.getResponseHeader("Content-Encoding"))&&"gzip"===
v;var t=1048576;B||(t=q);var r=this;r.nb(A=>{var D=A*t,K=(A+1)*t-1;K=Math.min(K,q-1);if("undefined"==typeof r.La[A]){var ua=r.La;if(D>K)throw Error("invalid range ("+D+", "+K+") or no bytes requested!");if(K>q-1)throw Error("only "+q+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",c,!1);q!==t&&G.setRequestHeader("Range","bytes="+D+"-"+K);G.responseType="arraybuffer";G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");G.send(null);if(!(200<=G.status&&
300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);D=void 0!==G.response?new Uint8Array(G.response||[]):hb(G.responseText||"");ua[A]=D}if("undefined"==typeof r.La[A])throw Error("doXHR failed!");return r.La[A]});if(l||!q)t=q=1,t=q=this.Va(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");this.eb=q;this.cb=t;this.Wa=!0}get length(){this.Wa||this.fb();return this.eb}get chunkSize(){this.Wa||this.fb();return this.cb}}if("undefined"!=
typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;var k=void 0}else k=c,g=void 0;var p=dc(a,b,d,e);g?p.Ga=g:k&&(p.Ga=null,p.url=k);Object.defineProperties(p,{Ja:{get:function(){return this.Ga.length}}});var n={};Object.keys(p.Ia).forEach(l=>{var q=p.Ia[l];n[l]=(...v)=>{fc(p);return q(...v)}});n.read=(l,q,v,B,t)=>{fc(p);l=l.node.Ga;if(t>=l.length)q=0;else{B=Math.min(l.length-t,B);if(l.slice)for(var r=
0;r<B;r++)q[v+r]=l[t+r];else for(r=0;r<B;r++)q[v+r]=l.get(t+r);q=B}return q};n.ab=()=>{fc(p);Da();throw new J(48);};p.Ia=n;return p}var U={};function hc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":R(a).path;if(0==b.length)throw new J(44);return a+"/"+b}
var Wa=void 0,ic=0,jc={},kc=a=>{a instanceof Ia||"unwind"==a||ma(1,a)},lc=a=>{wa=a;Na||0<ic||(h.onExit?.(a),va=!0);ma(a,new Ia(a))},oc=a=>{wa=a;if(!(Na||0<ic)){mc();Ab=!1;nc(0);for(var b of yb)b&&Zb(b);ya=!0}lc(a)},pc=a=>{if(!ya&&!va)try{if(a(),!(ya||Na||0<ic))try{oc(wa)}catch(b){kc(b)}}catch(b){kc(b)}},qc=a=>{Na=!1;ic=0;oc(a)},rc={},tc=()=>{if(!sc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||
"C").replace("-","_")+".UTF-8",_:la||"./this.program"},b;for(b in rc)void 0===rc[b]?delete a[b]:a[b]=rc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);sc=c}return sc},sc,vc=a=>{var b=gb(a)+1,c=uc(b);I(a,w,c,b);return c},wc=[],xc,V=a=>{var b=wc[a];b||(wc[a]=b=xc.get(a));return b},yc=(a,b,c,d)=>{var e={string:n=>{var l=0;null!==n&&void 0!==n&&0!==n&&(l=vc(n));return l},array:n=>{var l=uc(n.length);u.set(n,l);return l}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var p=e[c[k]];p?(0===g&&
(g=W()),f[k]=p(d[k])):f[k]=d[k]}c=a(...f);return c=function(n){0!==g&&X(g);return"string"===b?n?H(w,n):"":"boolean"===b?!!n:n}(c)};P=Array(4096);Qb(L,"/");S("/tmp");S("/home");S("/home/web_user");(function(){S("/dev");kb(259,{read:()=>0,write:(d,e,f,g)=>g,Oa:()=>0});Tb("/dev/null",259);jb(1280,mb);jb(1536,nb);Tb("/dev/tty",1280);Tb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(bb(a),b=a.byteLength);return a[--b]};T("/dev","random",c);T("/dev","urandom",c);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");Qb({Na(){var b=qb(a,"fd",16895,73);b.Ia={Oa:L.Ia.Oa};b.Ha={lookup(c,d){c=+d;var e=R(c);c={parent:null,Na:{lb:"fake"},Ha:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(yb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();L.hb=new J(44);L.hb.stack="<generic error, no stack>";
h.wasmMemory?ta=h.wasmMemory:ta=new WebAssembly.Memory({initial:(h.INITIAL_MEMORY||16777216)/65536,maximum:32768});za();h.noExitRuntime&&(Na=h.noExitRuntime);h.preloadPlugins&&(tb=h.preloadPlugins);h.print&&(ra=h.print);h.printErr&&(m=h.printErr);h.wasmBinary&&(sa=h.wasmBinary);h.arguments&&(ia=h.arguments);h.thisProgram&&(la=h.thisProgram);h.addRunDependency=Ba;h.removeRunDependency=Ca;
h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>yc(a,b,c,f)};h.FS_createPreloadedFile=(a,b,c,d,e,f,g,k,p,n)=>{function l(B){function t(r){n?.();k||ec(a,b,r,d,e,p);f?.();Ca(v)}ub(B,q,t,()=>{g?.();Ca(v)})||t(B)}var q=b?cb(Ya(a+"/"+b)):a,v=`cp ${q}`;Ba(v);"string"==typeof c?sb(c).then(l,g):l(c)};h.FS_unlink=(...a)=>Wb(...a);h.FS_createPath=(...a)=>bc(...a);h.FS_createDevice=(...a)=>T(...a);h.FS_createDataFile=(...a)=>ec(...a);
h.FS_createLazyFile=(...a)=>gc(...a);h._emscripten_force_exit=qc;
var nd={n:a=>{var b=new Sa(a);0==u[b.Ma+12]&&(u[b.Ma+12]=1,Pa--);u[b.Ma+13]=0;Oa.push(b);zc(a);return Ac(a)},q:()=>{Y(0,0);var a=Oa.pop();Bc(a.ib);E=0},b:()=>Va([]),f:a=>Va([a]),o:(a,b)=>Va([a,b]),K:()=>{var a=Oa.pop();a||Da("no exception to throw");var b=a.ib;0==u[a.Ma+13]&&(Oa.push(a),u[a.Ma+13]=1,u[a.Ma+12]=0,Pa++);E=b;throw E;},s:(a,b,c)=>{Ra(new Sa(a),b,c);E=a;Pa++;throw E;},oa:()=>Pa,g:a=>{E=E||a;throw E;},L:function(a,b,c){Wa=c;try{var d=R(a);switch(b){case 0:var e=F();if(0>e)break;for(;yb[e];)e++;
return Ob(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=F(),d.flags|=e,0;case 12:return e=F(),xa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.Ka}},S:function(a,b){try{if(0===b)return-28;var c=gb("/")+1;if(b<c)return-68;I("/",w,a,b);return c}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.Ka}},na:function(a,b,c){Wa=c;try{var d=R(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;
if(d.tty.Sa.pb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=F();x[e>>2]=25856;x[e+4>>2]=5;x[e+8>>2]=191;x[e+12>>2]=35387;for(var f=0;32>f;f++)u[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Sa.qb)for(e=F(),a=[],f=0;32>f;f++)a.push(u[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=F();return x[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=F();if(!d.Ia.ob)throw new J(59);
return d.Ia.ob(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Sa.rb&&(f=[24,80],e=F(),xa[e>>1]=f[0],xa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof U||"ErrnoError"!==g.name)throw g;return-g.Ka}},pa:function(a,b,c,d){Wa=d;try{b=b?H(w,b):"";b=hc(a,b);var e=d?F():0;return Yb(b,c,e).fd}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.Ka}},da:function(a,b,c,d){try{b=b?H(w,b):"";d=d?H(w,d):"";
b=hc(a,b);d=hc(c,d);a=b;var e=Za(a),f=Za(d),g=$a(a),k=$a(d);var p=Q(a,{parent:!0});var n=p.node;p=Q(d,{parent:!0});var l=p.node;if(!n||!l)throw new J(44);if(n.Na!==l.Na)throw new J(75);var q=N(n,g),v=db(a,f);if("."!==v.charAt(0))throw new J(28);v=db(d,e);if("."!==v.charAt(0))throw new J(55);try{var B=N(l,k)}catch(A){}if(q!==B){var t=M(q.mode),r=Lb(n,g,t);if(r)throw new J(r);if(r=B?Lb(l,k,t):Kb(l,k))throw new J(r);if(!n.Ha.rename)throw new J(63);if(q.Ta||B&&B.Ta)throw new J(10);if(l!==n&&(r=Ib(n,"w")))throw new J(r);
rb(q);try{n.Ha.rename(q,l,k),q.parent=l}catch(A){throw A;}finally{Hb(q)}}return 0}catch(A){if("undefined"==typeof U||"ErrnoError"!==A.name)throw A;return-A.Ka}},ea:function(a){try{return a=a?H(w,a):"",Vb(a),0}catch(b){if("undefined"==typeof U||"ErrnoError"!==b.name)throw b;return-b.Ka}},ga:function(a,b){try{a=a?H(w,a):"";var c=Q(a,{Xa:!0}).node;var d=Mb(c.Ha.Ra)(c);x[b>>2]=d.dev;x[b+4>>2]=d.mode;y[b+8>>2]=d.nlink;x[b+12>>2]=d.uid;x[b+16>>2]=d.gid;x[b+20>>2]=d.rdev;z[b+24>>3]=BigInt(d.size);x[b+32>>
2]=4096;x[b+36>>2]=d.blocks;var e=d.atime.getTime(),f=d.mtime.getTime(),g=d.ctime.getTime();z[b+40>>3]=BigInt(Math.floor(e/1E3));y[b+48>>2]=e%1E3*1E6;z[b+56>>3]=BigInt(Math.floor(f/1E3));y[b+64>>2]=f%1E3*1E6;z[b+72>>3]=BigInt(Math.floor(g/1E3));y[b+80>>2]=g%1E3*1E6;z[b+88>>3]=BigInt(d.ino);return 0}catch(k){if("undefined"==typeof U||"ErrnoError"!==k.name)throw k;return-k.Ka}},fa:function(a,b,c){try{return b=b?H(w,b):"",b=hc(a,b),0===c?Wb(b):512===c?Vb(b):Da("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==
typeof U||"ErrnoError"!==d.name)throw d;return-d.Ka}},ca:()=>Da(""),aa:()=>{Na=!1;ic=0},ba:(a,b)=>{jc[a]&&(clearTimeout(jc[a].id),delete jc[a]);if(!b)return 0;var c=setTimeout(()=>{delete jc[a];pc(()=>Cc(a,performance.now()))},b);jc[a]={id:c,Ib:b};return 0},ha:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();y[a>>2]=60*Math.max(f,e);x[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/
60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(I(a,w,c,17),I(b,w,d,17)):(I(a,w,d,17),I(b,w,c,17))},M:function(a,b,c){if(!(0<=a&&3>=a))return 28;z[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},_:qc,N:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ta.buffer.byteLength+65535)/65536|0;try{ta.grow(d);za();var e=1;
break a}catch(f){}e=void 0}if(e)return!0}return!1},ia:(a,b)=>{var c=0,d=0,e;for(e of tc()){var f=b+c;y[a+d>>2]=f;c+=I(e,w,f,Infinity)+1;d+=4}return 0},ja:(a,b)=>{var c=tc();y[a>>2]=c.length;a=0;for(var d of c)a+=gb(d)+1;y[b>>2]=a;return 0},Y:oc,I:function(a){try{var b=R(a);Zb(b);return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return c.Ka}},ma:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var f,g=b=0;g<c;g++){var k=y[a>>2],p=y[a+4>>2];a+=8;var n=e,l=k,q=p,v=f,B=u;if(0>q||0>
v)throw new J(28);if(null===n.fd)throw new J(8);if(1===(n.flags&2097155))throw new J(8);if(M(n.node.mode))throw new J(31);if(!n.Ia.read)throw new J(28);var t="undefined"!=typeof v;if(!t)v=n.position;else if(!n.seekable)throw new J(70);var r=n.Ia.read(n,B,l,q,v);t||(n.position+=r);var A=r;if(0>A){var D=-1;break a}b+=A;if(A<p)break;"undefined"!=typeof f&&(f+=A)}D=b}y[d>>2]=D;return 0}catch(K){if("undefined"==typeof U||"ErrnoError"!==K.name)throw K;return K.Ka}},ka:function(a,b,c,d){b=-9007199254740992>
b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=R(a);$b(e,b,c);z[d>>3]=BigInt(e.position);e.$a&&0===b&&0===c&&(e.$a=null);return 0}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return f.Ka}},la:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var f,g=b=0;g<c;g++){var k=y[a>>2],p=y[a+4>>2];a+=8;var n=ac(e,u,k,p,f);if(0>n){var l=-1;break a}b+=n;if(n<p)break;"undefined"!=typeof f&&(f+=n)}l=b}y[d>>2]=l;return 0}catch(q){if("undefined"==typeof U||"ErrnoError"!==q.name)throw q;
return q.Ka}},W:Dc,O:Ec,Z:Fc,d:Gc,v:Hc,c:Ic,e:Jc,u:Kc,Q:Lc,r:Mc,p:Nc,z:Oc,A:Pc,J:Qc,F:Rc,H:Sc,R:Tc,T:Uc,t:Vc,U:Wc,V:Xc,P:Yc,h:Zc,l:$c,i:ad,j:bd,k:cd,m:dd,C:ed,x:fd,B:gd,E:hd,D:jd,X:kd,G:ld,y:md,w:a=>a,a:ta,$:lc},Z=await (async function(){function a(d){Z=d.exports;xc=Z.ta;Ca("wasm-instantiate");return Z}Ba("wasm-instantiate");var b={a:nd};if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});Ea=Ea??h.locateFile?h.locateFile("rapfi-single.wasm",na):na+
"rapfi-single.wasm";try{var c=await Ha(b);return a(c.instance)}catch(d){return ba(d),Promise.reject(d)}}());h._gomocupLoopOnce=Z.ra;var od=h._main=Z.sa,mc=Z.ua,nc=Z.va,Cc=Z.wa,Y=Z.xa,Ta=Z.ya,X=Z.za,uc=Z.Aa,W=Z.Ba,Bc=Z.Ca,zc=Z.Da,Ua=Z.Ea,Ac=Z.Fa;function Ic(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Jc(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}
function bd(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function ad(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Zc(a){var b=W();try{V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function Gc(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Pc(a,b,c,d,e,f,g){var k=W();try{return V(a)(b,c,d,e,f,g)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}
function $c(a,b){var c=W();try{V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function cd(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function Vc(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Fc(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function Oc(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}
function dd(a,b,c,d,e,f){var g=W();try{V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}function Kc(a,b,c,d,e){var f=W();try{return V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function jd(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function Hc(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function ld(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}
function md(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Mc(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}function ed(a,b,c,d,e,f,g){var k=W();try{V(a)(b,c,d,e,f,g)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}function Nc(a,b,c,d,e,f,g){var k=W();try{return V(a)(b,c,d,e,f,g)}catch(p){X(k);if(p!==p+0)throw p;Y(1,0)}}function fd(a,b,c,d,e,f,g,k){var p=W();try{V(a)(b,c,d,e,f,g,k)}catch(n){X(p);if(n!==n+0)throw n;Y(1,0)}}
function kd(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function Dc(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Xc(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0);return 0n}}function Wc(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0);return 0n}}function Uc(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}
function Tc(a,b,c,d,e){var f=W();try{return V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function Sc(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}function Lc(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}function Qc(a,b,c,d,e,f,g,k){var p=W();try{return V(a)(b,c,d,e,f,g,k)}catch(n){X(p);if(n!==n+0)throw n;Y(1,0)}}
function Rc(a,b,c,d,e,f,g,k,p,n,l,q){var v=W();try{return V(a)(b,c,d,e,f,g,k,p,n,l,q)}catch(B){X(v);if(B!==B+0)throw B;Y(1,0)}}function gd(a,b,c,d,e,f,g,k,p,n,l){var q=W();try{V(a)(b,c,d,e,f,g,k,p,n,l)}catch(v){X(q);if(v!==v+0)throw v;Y(1,0)}}function hd(a,b,c,d,e,f,g,k,p,n,l,q,v,B,t,r){var A=W();try{V(a)(b,c,d,e,f,g,k,p,n,l,q,v,B,t,r)}catch(D){X(A);if(D!==D+0)throw D;Y(1,0)}}function Yc(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0);return 0n}}
function Ec(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function pd(a=[]){a.unshift(la);var b=a.length,c=uc(4*(b+1)),d=c;a.forEach(f=>{y[d>>2]=vc(f);d+=4});y[d>>2]=0;try{var e=od(b,c);oc(e,!0)}catch(f){kc(f)}}
function qd(a=ia){function b(){h.calledRun=!0;if(!va){h.noFSInit||Ab||ha();Z.qa();Bb=!1;aa(h);h.onRuntimeInitialized?.();h.noInitialRun||pd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ka.push(c)}Ja(Ka)}}if(0<C)Aa=qd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ma();Ja(La);0<C?Aa=qd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();qd();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Rapfi;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = Rapfi;
} else if (typeof define === 'function' && define['amd'])
  define([], () => Rapfi);
