var Rapfi = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,u=ea&&self.name?.startsWith("em-pthread");if(n){var fa=require("worker_threads");global.Worker=fa.Worker;u=(ea=!fa.pc)&&"em-pthread"==fa.workerData}h.expectedDataFileDownloads??(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof u&&u||a)){var b="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;(function(c){function d(l,q,A,B){b?require("fs").readFile(l,(t,r)=>{t?B(t):A(r.buffer)}):(h.dataFileDownloads??(h.dataFileDownloads={}),fetch(l).catch(t=>Promise.reject(Error(`Network Error: ${l}`,{cause:t}))).then(t=>{if(!t.ok)return Promise.reject(Error(`${t.status}: ${t.url}`));
if(!t.body&&t.arrayBuffer)return t.arrayBuffer().then(A);const r=t.body.getReader(),C=()=>r.read().then(I).catch(T=>Promise.reject(Error(`Unexpected error while handling : ${t.url} ${T}`,{cause:T}))),H=[],Q=Number(t.headers.get("Content-Length")??q);let Ja=0;const I=({done:T,value:Lb})=>{if(T){var ra=new Uint8Array(H.map(db=>db.length).reduce((db,wd)=>db+wd,0));T=0;for(var sa of H)ra.set(sa,T),T+=sa.length;A(ra.buffer)}else{H.push(Lb);Ja+=Lb.length;h.dataFileDownloads[l]={loaded:Ja,total:Q};T=sa=
0;for(ra of Object.values(h.dataFileDownloads))sa+=ra.loaded,T+=ra.total;h.setStatus?.(`Downloading data... (${sa}/${T})`);return C()}};h.setStatus?.("Downloading data...");return C()}))}function e(l){console.error("package error:",l)}function f(l){function q(r,C,H){this.start=r;this.end=C;this.audio=H}function A(r){if(!r)throw"Loading data file failed."+Error().stack;if(r.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;r=new Uint8Array(r);q.prototype.tb=r;
r=c.files;for(var C=0;C<r.length;++C)q.prototype.gb[r[C].filename].onload();l.removeRunDependency("datafile_rapfi-single.data")}q.prototype={gb:{},open:function(r,C){this.name=C;this.gb[C]=this;l.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.sb(this.tb.subarray(this.start,this.end))},sb:function(r){l.FS_createDataFile(this.name,null,r,!0,!0,!0);l.removeRunDependency(`fp ${this.name}`);this.gb[this.name]=null}};for(var B=c.files,t=0;t<B.length;++t)(new q(B[t].start,
B[t].end,B[t].audio||0)).open("GET",B[t].filename);l.addRunDependency("datafile_rapfi-single.data");l.preloadResults??(l.preloadResults={});l.preloadResults["rapfi-single.data"]={nc:!1};p?(A(p),p=null):m=A}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+
"/");var g=h.locateFile?h.locateFile("rapfi-single.data",""):"rapfi-single.data",k=c.remote_package_size,m=null,p=h.getPreloadedPackage?h.getPreloadedPackage(g,k):null;p||d(g,k,l=>{m?(m(l),m=null):p=l},e);h.calledRun?f(h):(h.preRun??(h.preRun=[])).push(f)})({files:[{filename:"/classical210901.toml",start:0,end:5735},{filename:"/classical220723.toml",start:5735,end:11470},{filename:"/config.toml",start:11470,end:18183},{filename:"/mix9svqfreestyle_bsmix.bin.lz4",start:18183,end:10048581},
{filename:"/mix9svqrenju_bs15_black.bin.lz4",start:10048581,end:20032753},{filename:"/mix9svqrenju_bs15_white.bin.lz4",start:20032753,end:29877697},{filename:"/mix9svqstandard_bs15.bin.lz4",start:29877697,end:40223472},{filename:"/model210901.bin",start:40223472,end:40246676},{filename:"/model220723.bin",start:40246676,end:40306406}],remote_package_size:40306406})}})();h.sendCommand=h.sendCommand||null;h.terminate=h.terminate||null;h.onReceiveStdout=h.onReceiveStdout||(a=>console.log(a));
h.onReceiveStderr=h.onReceiveStderr||(a=>console.error(a));h.onExit=h.onExit||(a=>console.log("exited with code "+a));h.noExitRuntime=!0;h.preRun||(h.preRun=[]);
h.preRun.push(function(){let a=[];var b="",c=0;let d="",e="";const f=h.onReceiveStdout,g=h.onReceiveStderr;ha(function(){return c<b.length?b.charCodeAt(c++):0<a.length?(b=a.shift(),c=0,b.charCodeAt(c++)):null},function(m){m&&10!=m?d+=String.fromCharCode(m):(f(d),d="")},function(m){m&&10!=m?e+=String.fromCharCode(m):(g(e),e="")});const k=h.cwrap("gomocupLoopOnce","number",[]);h.sendCommand=function(m){a.push(m+"\n");k()};h.terminate=function(){h._emscripten_force_exit(0)}});
var ia=[],ja="./this.program",ka=(a,b)=>{throw b;};"undefined"!=typeof __filename?_scriptName=__filename:ea&&(_scriptName=self.location.href);var la="",ma,na;
if(n){var fs=require("fs");require("path");la=__dirname+"/";na=a=>{a=oa(a)?new URL(a):a;return fs.readFileSync(a)};ma=async a=>{a=oa(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ja=process.argv[1].replace(/\\/g,"/"));ia=process.argv.slice(2);ka=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea){try{la=(new URL(".",_scriptName)).href}catch{}n||(ea&&(na=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ma=async a=>{if(oa(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);})}var pa=console.log.bind(console),qa=console.error.bind(console);
if(n){var ta=require("util"),ua=a=>"object"==typeof a?ta.inspect(a):a;pa=(...a)=>fs.writeSync(1,a.map(ua).join(" ")+"\n");qa=(...a)=>fs.writeSync(2,a.map(ua).join(" ")+"\n")}var va=pa,v=qa,wa,w,xa,ya=!1,za,Aa,Ba,Ca,Da,Ea,x,Fa,Ga=!1,oa=a=>a.startsWith("file://");function y(){w.buffer!=Aa.buffer&&z();return Aa}function Ha(){w.buffer!=Aa.buffer&&z();return Ba}function Ia(){w.buffer!=Aa.buffer&&z();return Ca}function D(){w.buffer!=Aa.buffer&&z();return Da}
function E(){w.buffer!=Aa.buffer&&z();return Ea}function Ka(){w.buffer!=Aa.buffer&&z();return Fa}var La;if(n&&u){var Ma=fa.parentPort;Ma.on("message",a=>global.onmessage?.({data:a}));Object.assign(globalThis,{self:global,postMessage:a=>Ma.postMessage(a)})}
if(u){var Na=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.ob;if("load"===d){let e=[];self.onmessage=f=>e.push(f);self.startWorker=()=>{postMessage({ob:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Ob)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({ob:"callHandler",Nb:f,args:g})},"print"==f&&(va=h[f]),"printErr"==f&&(v=h[f]);w=c.cc;z();La(c.dc)}else if("run"===d){Oa(c.kb);Pa(c.kb,0,0,1,0,0);Qa();Ra(c.kb);Na||=!0;try{Sa(c.Zb,c.xb)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?Na&&Ta():d&&(v(`worker: received unknown command ${d}`),v(c)))}catch(e){throw Ua(),e;}}self.onmessage=a}function z(){var a=w.buffer;Aa=new Int8Array(a);Ca=new Int16Array(a);Ba=new Uint8Array(a);new Uint16Array(a);Da=new Int32Array(a);Ea=new Uint32Array(a);new Float32Array(a);Fa=new Float64Array(a);x=new BigInt64Array(a);new BigUint64Array(a)}function Va(){u?startWorker(h):(h.noFSInit||Wa||ha(),F.Ca(),Xa=!1)}var Ya=0,Za=null;
function $a(){Ya++;h.monitorRunDependencies?.(Ya)}function ab(){Ya--;h.monitorRunDependencies?.(Ya);if(0==Ya&&Za){var a=Za;Za=null;a()}}function bb(a){h.onAbort?.(a);a="Aborted("+a+")";v(a);ya=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var cb;async function eb(a){if(!wa)try{var b=await ma(a);return new Uint8Array(b)}catch{}if(a==cb&&wa)a=new Uint8Array(wa);else if(na)a=na(a);else throw"both async and sync fetching of the wasm failed";return a}
async function fb(a,b){try{var c=await eb(a);return await WebAssembly.instantiate(c,b)}catch(d){v(`failed to asynchronously prepare wasm: ${d}`),bb(d)}}async function gb(a){var b=cb;if(!wa&&"function"==typeof WebAssembly.instantiateStreaming&&!oa(b)&&!n)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){v(`wasm streaming compile failed: ${d}`),v("falling back to ArrayBuffer instantiation")}return fb(b,a)}
function hb(){ib={m:jb,q:kb,b:lb,f:mb,n:nb,N:ob,t:pb,qa:qb,wa:rb,g:sb,O:tb,Ba:ub,pa:vb,ra:wb,fa:xb,ga:yb,ia:zb,ha:Ab,sa:Bb,Aa:Cb,va:Db,ya:Eb,ca:Fb,Q:Gb,za:Ra,M:Hb,da:Ib,ja:Jb,xa:Kb,R:Mb,S:Nb,la:Ob,C:Pb,ea:Qb,ua:Rb,Z:Sb,ka:Tb,ma:Ub,K:Vb,P:Wb,oa:Xb,na:Yb,ta:Zb,$:$b,T:ac,F:bc,e:cc,w:dc,c:ec,d:fc,s:gc,V:hc,r:ic,p:jc,A:kc,B:lc,L:mc,H:nc,J:oc,W:pc,X:qc,u:rc,Y:sc,_:tc,U:uc,i:vc,k:wc,h:xc,j:yc,l:zc,o:Ac,y:Bc,x:Cc,D:Dc,G:Ec,E:Fc,aa:Gc,I:Hc,z:Ic,v:Jc,a:w,ba:Kc};return{a:ib}}
class Lc{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Mc=a=>{a.terminate();a.onmessage=()=>{}},Nc=a=>{for(;0<a.length;)a.shift()(h)},Oc=[],Uc=a=>{0==Pc.length&&(Qc(),Rc(Pc[0]));var b=Pc.pop();if(!b)return 6;Sc.push(b);Tc[a.kb]=b;b.kb=a.kb;var c={ob:"run",Zb:a.Yb,xb:a.xb,kb:a.kb};n&&b.unref();b.postMessage(c,a.Mb);return 0},G=0,Sb=()=>J||0<G,M=(a,b,...c)=>{for(var d=2*c.length,e=K(),f=Vc(8*d),g=f>>3,k=0;k<c.length;k++){var m=c[k];"bigint"==typeof m?(x[g+2*k]=1n,x[g+2*k+1]=m):(x[g+2*k]=0n,Ka()[g+2*k+1]=m)}a=Wc(a,0,d,f,b);L(e);return a};
function Kc(a){if(u)return M(0,1,a);za=a;J||0<G||(Xc(),h.onExit?.(a),ya=!0);ka(a,new Lc(a))}function Yc(a){if(u)return M(1,0,a);--G;Vb(a)}var Vb=a=>{za=a;if(u)throw Yc(a),"unwind";if(!(J||0<G||u)){Zc();Wa=!1;$c(0);for(var b of ad)b&&bd(b);Xc();Ga=!0}Kc(a)},Pc=[],Sc=[],cd=[],Tc={};function dd(){for(var a=4;a--;)Qc();Oc.push(()=>{$a("loading-workers");ed(()=>ab("loading-workers"))})}
var Xc=()=>{for(var a of Sc)Mc(a);for(a of Pc)Mc(a);Pc=[];Sc=[];Tc={}},gd=a=>{var b=a.kb;delete Tc[b];Pc.push(a);Sc.splice(Sc.indexOf(a),1);a.kb=0;n&&a.unref();fd(b)};function Qa(){cd.forEach(a=>a())}
var Rc=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.ob;if(f.wb&&f.wb!=hd()){var k=Tc[f.wb];k?k.postMessage(f,f.Mb):v(`Internal error! Worker sent a message "${g}" to target pthread ${f.wb}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ta();else if("spawnThread"===g)Uc(f);else if("cleanupThread"===g)gd(Tc[f.$b]);else if("loaded"===g)a.loaded=!0,n&&!a.kb&&a.unref(),b(a);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)h[f.Nb](...f.args);else g&&v(`worker sent an unknown command ${g}`)};
a.onerror=f=>{v(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};n&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({ob:"load",Ob:c,cc:w,dc:xa})});function ed(a){u?a():Promise.all(Pc.map(Rc)).then(a)}
function Qc(){var a=_scriptName;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{workerData:"em-pthread",name:"em-pthread"});Pc.push(a)}
var jd=[],Oa=a=>{z();var b=E()[a+52>>2];a=E()[a+56>>2];kd(b,b-a);L(b)},ld=[],md,N=a=>{var b=ld[a];b||(ld[a]=b=md.get(a));return b},Sa=(a,b)=>{J=G=0;a=N(a)(b);J||0<G?za=a:nd(a)},J=!1,od=[],pd=0,jb=a=>{var b=new qd(a);if(0==y()[b.hb+12]){var c=1;y()[b.hb+12]=c;pd--}c=0;y()[b.hb+13]=c;od.push(b);rd(a);return sd(a)},td=0,kb=()=>{O(0,0);var a=od.pop();ud(a.Fb);td=0};function vd(a,b,c){E()[a.hb+16>>2]=0;E()[a.hb+4>>2]=b;E()[a.hb+8>>2]=c}class qd{constructor(a){this.Fb=a;this.hb=a-24}}
var zd=a=>{var b=td;if(!b)return xd(0),0;var c=new qd(b);E()[c.hb+16>>2]=b;var d=E()[c.hb+4>>2];if(!d)return xd(0),b;for(var e of a){if(0===e||e===d)break;if(yd(e,d,c.hb+16))return xd(e),b}xd(d);return b},lb=()=>zd([]),mb=a=>zd([a]),nb=(a,b)=>zd([a,b]),ob=()=>{var a=od.pop();a||bb("no exception to throw");var b=a.Fb;if(0==y()[a.hb+13]){od.push(a);var c=1;y()[a.hb+13]=c;c=0;y()[a.hb+12]=c;pd++}td=b;throw td;},pb=(a,b,c)=>{vd(new qd(a),b,c);td=a;pd++;throw td;},qb=()=>pd;
function Ad(a,b,c,d){return u?M(2,1,a,b,c,d):rb(a,b,c,d)}
var rb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(u&&0===e.length)return Ad(a,b,c,d);a={Yb:c,kb:a,xb:d,Mb:e};return u?(a.ob="spawnThread",postMessage(a,e),0):Uc(a)},sb=a=>{td||=a;throw td;},P=()=>{var a=D()[+Bd>>2];Bd+=4;return a},Cd=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Dd=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Cd(a.split("/").filter(d=>
!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ed=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Fd=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Gd=()=>{if(n){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>b.set(crypto.getRandomValues(new Uint8Array(b.byteLength)))},Hd=a=>{(Hd=Gd())(a)},Id=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=
typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Cd(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Jd=(a,b)=>{function c(g){for(var k=0;k<g.length&&""===g[k];k++);for(var m=g.length-1;0<=m&&""===g[m];m--);return k>m?[]:g.slice(k,m-k+1)}a=Id(a).slice(1);b=Id(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");
d=d.concat(b.slice(e));return d.join("/")},Kd=(a,b=0)=>{for(var c=b+NaN,d="";!(b>=c);){var e=a[b++];if(!e)break;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ld=[],Md=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:
55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Nd=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},Od=a=>{var b=Array(Md(a)+1);a=Nd(a,
b,0,b.length);b.length=a;return b},Pd=[];function Qd(a,b){Pd[a]={input:[],output:[],pb:b};Rd(a,Sd)}
var Sd={open(a){var b=Pd[a.node.rdev];if(!b)throw new R(43);a.tty=b;a.seekable=!1},close(a){a.tty.pb.fsync(a.tty)},fsync(a){a.tty.pb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.pb.Ib)throw new R(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.pb.Ib(a.tty)}catch(k){throw new R(29);}if(void 0===g&&0===e)throw new R(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.pb.Bb)throw new R(60);try{for(var e=0;e<d;e++)a.tty.pb.Bb(a.tty,b[c+e])}catch(f){throw new R(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Td={Ib(){a:{if(!Ld.length){var a=null;if(n){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ld=Od(a)}a=Ld.shift()}return a},Bb(a,b){null===b||10===b?(va(Kd(a.output)),a.output=[]):0!=
b&&a.output.push(b)},fsync(a){0<a.output?.length&&(va(Kd(a.output)),a.output=[])},Rb(){return{ic:25856,kc:5,hc:191,jc:35387,fc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Sb(){return 0},Tb(){return[24,80]}},Ud={Bb(a,b){null===b||10===b?(v(Kd(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(v(Kd(a.output)),a.output=[])}},S={mb:null,jb(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new R(63);
S.mb||(S.mb={dir:{node:{ib:S.ab.ib,nb:S.ab.nb,lookup:S.ab.lookup,vb:S.ab.vb,rename:S.ab.rename,unlink:S.ab.unlink,rmdir:S.ab.rmdir,readdir:S.ab.readdir,symlink:S.ab.symlink},stream:{lb:S.cb.lb}},file:{node:{ib:S.ab.ib,nb:S.ab.nb},stream:{lb:S.cb.lb,read:S.cb.read,write:S.cb.write,Ab:S.cb.Ab,Lb:S.cb.Lb}},link:{node:{ib:S.ab.ib,nb:S.ab.nb,readlink:S.ab.readlink},stream:{}},Cb:{node:{ib:S.ab.ib,nb:S.ab.nb},stream:Vd}});c=Wd(a,b,c,d);U(c.mode)?(c.ab=S.mb.dir.node,c.cb=S.mb.dir.stream,c.bb={}):32768===
(c.mode&61440)?(c.ab=S.mb.file.node,c.cb=S.mb.file.stream,c.eb=0,c.bb=null):40960===(c.mode&61440)?(c.ab=S.mb.link.node,c.cb=S.mb.link.stream):8192===(c.mode&61440)&&(c.ab=S.mb.Cb.node,c.cb=S.mb.Cb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.bb[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},oc(a){return a.bb?a.bb.subarray?a.bb.subarray(0,a.eb):new Uint8Array(a.bb):new Uint8Array(0)},ab:{ib(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=
a.rdev;U(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.eb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},nb(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.eb!=b&&(0==b?(a.bb=null,a.eb=0):(c=a.bb,a.bb=new Uint8Array(b),c&&a.bb.set(c.subarray(0,Math.min(b,a.eb))),a.eb=b)))},lookup(){throw S.Db;
},vb(a,b,c,d){return S.createNode(a,b,c,d)},rename(a,b,c){try{var d=V(b,c)}catch(f){}if(d){if(U(a.mode))for(var e in d.bb)throw new R(55);Xd(d)}delete a.parent.bb[a.name];b.bb[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.bb[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=V(a,b),d;for(d in c.bb)throw new R(55);delete a.bb[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.bb)]},symlink(a,b,c){a=S.createNode(a,b,41471,0);a.link=
c;return a},readlink(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},cb:{read(a,b,c,d,e){var f=a.node.bb;if(e>=a.node.eb)return 0;a=Math.min(a.node.eb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===y().buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.bb||a.bb.subarray)){if(f)return a.bb=b.subarray(c,c+d),a.eb=d;if(0===a.eb&&0===e)return a.bb=b.slice(c,c+d),a.eb=d;if(e+d<=
a.eb)return a.bb.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.bb?a.bb.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.bb,a.bb=new Uint8Array(f),0<a.eb&&a.bb.set(g.subarray(0,a.eb),0));if(a.bb.subarray&&b.subarray)a.bb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.bb[e+f]=b[c+f];a.eb=Math.max(a.eb,e+d);return d},lb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.eb);if(0>b)throw new R(28);return b},Ab(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new R(43);a=a.node.bb;if(e&2||!a||a.buffer!==y().buffer){d=!0;bb();e=void 0;if(!e)throw new R(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);y().set(a,e)}}else d=!1,e=a.byteOffset;return{hb:e,ec:d}},Lb(a,b,c,d){S.cb.write(a,b,0,d,c,!1);return 0}}},Yd=async a=>{a=await ma(a);return new Uint8Array(a)},Zd=[],$d=(a,b,c,d)=>{"undefined"!=typeof Browser&&vd(Browser);var e=!1;Zd.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},
ae=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},be=null,ce={},ad=[],de=1,ee=null,Wa=!1,Xa=!0,fe={},R=class{name="ErrnoError";constructor(a){this.fb=a}},ge=class{gb={};node=null;get flags(){return this.gb.flags}set flags(a){this.gb.flags=a}get position(){return this.gb.position}set position(a){this.gb.position=a}},he=class{ab={};cb={};qb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.jb=a.jb;this.id=de++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===
(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Vb(){return U(this.mode)}get Ub(){return 8192===(this.mode&61440)}};
function W(a,b={}){if(!a)throw new R(44);b.yb??(b.yb=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=be,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ed(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=Dd(e+"/"+a[f]);try{d=V(d,a[f])}catch(k){if(44===k?.fb&&g&&b.Xb)return{path:e};throw k;}!d.qb||g&&!b.yb||(d=d.qb.root);if(40960===(d.mode&61440)&&(!g||b.ub)){if(!d.ab.readlink)throw new R(52);
d=d.ab.readlink(d);"/"===d.charAt(0)||(d=Ed(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new R(32);}function ie(a){for(var b;;){if(a===a.parent)return a=a.jb.Kb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function je(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ee.length}function ke(a){var b=je(a.parent.id,a.name);a.rb=ee[b];ee[b]=a}
function Xd(a){var b=je(a.parent.id,a.name);if(ee[b]===a)ee[b]=a.rb;else for(b=ee[b];b;){if(b.rb===a){b.rb=a.rb;break}b=b.rb}}function V(a,b){var c=U(a.mode)?(c=le(a,"x"))?c:a.ab.lookup?0:2:54;if(c)throw new R(c);for(c=ee[je(a.id,b)];c;c=c.rb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ab.lookup(a,b)}function Wd(a,b,c,d){a=new he(a,b,c,d);ke(a);return a}function U(a){return 16384===(a&61440)}function me(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function le(a,b){if(Xa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ne(a,b){if(!U(a.mode))return 54;try{return V(a,b),20}catch(c){}return le(a,"wx")}function oe(a,b,c){try{var d=V(a,b)}catch(e){return e.fb}if(a=le(a,"wx"))return a;if(c){if(!U(d.mode))return 54;if(d===d.parent||"/"===ie(d))return 10}else if(U(d.mode))return 31;return 0}function pe(a){if(!a)throw new R(63);return a}
function X(a){a=ad[a];if(!a)throw new R(8);return a}function qe(a,b=-1){a=Object.assign(new ge,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!ad[b])break a;throw new R(33);}a.fd=b;return ad[b]=a}function re(a,b=-1){a=qe(a,b);a.cb?.mc?.(a);return a}function se(a,b){var c=null?.cb.nb,d=c?null:a;c??=a.ab.nb;pe(c);c(d,b)}var Vd={open(a){a.cb=ce[a.node.rdev].cb;a.cb.open?.(a)},lb(){throw new R(70);}};function Rd(a,b){ce[a]={cb:b}}
function te(a,b){var c="/"===b;if(c&&be)throw new R(10);if(!c&&b){var d=W(b,{yb:!1});b=d.path;d=d.node;if(d.qb)throw new R(10);if(!U(d.mode))throw new R(54);}b={type:a,qc:{},Kb:b,Wb:[]};a=a.jb(b);a.jb=b;b.root=a;c?be=a:d&&(d.qb=b,d.jb&&d.jb.Wb.push(b))}function ue(a,b,c){var d=W(a,{parent:!0}).node;a=Fd(a);if(!a)throw new R(28);if("."===a||".."===a)throw new R(20);var e=ne(d,a);if(e)throw new R(e);if(!d.ab.vb)throw new R(63);return d.ab.vb(d,a,b,c)}
function ve(a,b=438){return ue(a,b&4095|32768,0)}function Y(a){return ue(a,16895,0)}function we(a,b,c){"undefined"==typeof c&&(c=b,b=438);return ue(a,b|8192,c)}function xe(a,b){if(!Id(a))throw new R(44);var c=W(b,{parent:!0}).node;if(!c)throw new R(44);b=Fd(b);var d=ne(c,b);if(d)throw new R(d);if(!c.ab.symlink)throw new R(63);c.ab.symlink(c,b,a)}
function ye(a){var b=W(a,{parent:!0}).node;a=Fd(a);var c=V(b,a),d=oe(b,a,!0);if(d)throw new R(d);if(!b.ab.rmdir)throw new R(63);if(c.qb)throw new R(10);b.ab.rmdir(b,a);Xd(c)}function ze(a){var b=W(a,{parent:!0}).node;if(!b)throw new R(44);a=Fd(a);var c=V(b,a),d=oe(b,a,!1);if(d)throw new R(d);if(!b.ab.unlink)throw new R(63);if(c.qb)throw new R(10);b.ab.unlink(b,a);Xd(c)}function Ae(a,b){a=W(a,{ub:!b}).node;return pe(a.ab.ib)(a)}
function Be(a,b){a="string"==typeof a?W(a,{ub:!0}).node:a;se(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),lc:void 0})}
function Ce(a,b,c=438){if(""===a)throw new R(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=W(a,{ub:!(b&131072),Xb:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new R(20);}else{if(e)throw new R(31);d=ue(a,c|511,0);f=!0}if(!d)throw new R(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!U(d.mode))throw new R(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:U(d.mode)&&("r"!==me(b)||b&576)?31:le(d,me(b)):44))throw new R(e);if(b&512&&!f){e=d;e="string"==typeof e?W(e,{ub:!0}).node:e;if(U(e.mode))throw new R(31);if(32768!==(e.mode&61440))throw new R(28);var g=le(e,"w");if(g)throw new R(g);se(e,{size:0,timestamp:Date.now()})}b&=-131713;e=qe({node:d,path:ie(d),flags:b,seekable:!0,position:0,cb:d.cb,ac:[],error:!1});e.cb.open&&e.cb.open(e);f&&Be(d,c&511);!h.logReadFiles||b&1||a in fe||(fe[a]=1);return e}
function bd(a){if(null===a.fd)throw new R(8);a.zb&&(a.zb=null);try{a.cb.close&&a.cb.close(a)}catch(b){throw b;}finally{ad[a.fd]=null}a.fd=null}function De(a,b,c){if(null===a.fd)throw new R(8);if(!a.seekable||!a.cb.lb)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.cb.lb(a,b,c);a.ac=[]}
function Ee(a,b,c,d,e,f){if(0>d||0>e)throw new R(28);if(null===a.fd)throw new R(8);if(0===(a.flags&2097155))throw new R(8);if(U(a.node.mode))throw new R(31);if(!a.cb.write)throw new R(28);a.seekable&&a.flags&1024&&De(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new R(70);b=a.cb.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function ha(a,b,c){Wa=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?Fe("/dev","stdin",a):xe("/dev/tty","/dev/stdin");b?Fe("/dev","stdout",null,b):xe("/dev/tty","/dev/stdout");c?Fe("/dev","stderr",null,c):xe("/dev/tty1","/dev/stderr");Ce("/dev/stdin",0);Ce("/dev/stdout",1);Ce("/dev/stderr",1)}function Ge(a,b){a="string"==typeof a?a:ie(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Dd(a+"/"+c);try{Y(d)}catch(e){if(20!=e.fb)throw e;}a=d}}return d}
function He(a,b,c,d){a=Dd(("string"==typeof a?a:ie(a))+"/"+b);return ve(a,ae(c,d))}function Ie(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:ie(a),g=b?Dd(a+"/"+b):a);a=ae(d,e);g=ve(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Be(g,a|146);b=Ce(g,577);Ee(b,c,0,c.length,0,f);bd(b);Be(g,a)}}
function Fe(a,b,c,d){a=Dd(("string"==typeof a?a:ie(a))+"/"+b);b=ae(!!c,!!d);Fe.Jb??(Fe.Jb=64);var e=Fe.Jb++<<8|0;Rd(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,m){for(var p=0,l=0;l<m;l++){try{var q=c()}catch(A){throw new R(29);}if(void 0===q&&0===p)throw new R(6);if(null===q||void 0===q)break;p++;g[k+l]=q}p&&(f.node.atime=Date.now());return p},write(f,g,k,m){for(var p=0;p<m;p++)try{d(g[k+p])}catch(l){throw new R(29);}m&&(f.node.mtime=f.node.ctime=Date.now());return p}});
return we(a,b,e)}function Je(a){if(!(a.Ub||a.Vb||a.link||a.bb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.bb=na(a.url),a.eb=a.bb.length}catch(b){throw new R(29);}}}
function Ke(a,b,c,d,e){class f{tb=!1;gb=[];sb=void 0;Gb=0;Eb=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.sb(l/this.chunkSize|0)[q]}}Pb(l){this.sb=l}Hb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),A,B=(A=l.getResponseHeader("Accept-Ranges"))&&"bytes"===A;l=(A=l.getResponseHeader("Content-Encoding"))&&"gzip"===
A;var t=1048576;B||(t=q);var r=this;r.Pb(C=>{var H=C*t,Q=(C+1)*t-1;Q=Math.min(Q,q-1);if("undefined"==typeof r.gb[C]){var Ja=r.gb;if(H>Q)throw Error("invalid range ("+H+", "+Q+") or no bytes requested!");if(Q>q-1)throw Error("only "+q+" bytes available! programmer error!");var I=new XMLHttpRequest;I.open("GET",c,!1);q!==t&&I.setRequestHeader("Range","bytes="+H+"-"+Q);I.responseType="arraybuffer";I.overrideMimeType&&I.overrideMimeType("text/plain; charset=x-user-defined");I.send(null);if(!(200<=I.status&&
300>I.status||304===I.status))throw Error("Couldn't load "+c+". Status: "+I.status);H=void 0!==I.response?new Uint8Array(I.response||[]):Od(I.responseText||"");Ja[C]=H}if("undefined"==typeof r.gb[C])throw Error("doXHR failed!");return r.gb[C]});if(l||!q)t=q=1,t=q=this.sb(0).length,va("LazyFiles on gzip forces download of the whole file when length is accessed");this.Gb=q;this.Eb=t;this.tb=!0}get length(){this.tb||this.Hb();return this.Gb}get chunkSize(){this.tb||this.Hb();return this.Eb}}if("undefined"!=
typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;var k=void 0}else k=c,g=void 0;var m=He(a,b,d,e);g?m.bb=g:k&&(m.bb=null,m.url=k);Object.defineProperties(m,{eb:{get:function(){return this.bb.length}}});var p={};Object.keys(m.cb).forEach(l=>{var q=m.cb[l];p[l]=(...A)=>{Je(m);return q(...A)}});p.read=(l,q,A,B,t)=>{Je(m);l=l.node.bb;if(t>=l.length)q=0;else{B=Math.min(l.length-t,B);if(l.slice)for(var r=
0;r<B;r++)q[A+r]=l[t+r];else for(r=0;r<B;r++)q[A+r]=l.get(t+r);q=B}return q};p.Ab=()=>{Je(m);bb();throw new R(48);};m.cb=p;return m}var Z={},Le=a=>a?Kd(Ha(),a):"";function Me(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":X(a).path;if(0==b.length){if(!c)throw new R(44);return a}return a+"/"+b}
function Ne(a,b){D()[a>>2]=b.dev;D()[a+4>>2]=b.mode;E()[a+8>>2]=b.nlink;D()[a+12>>2]=b.uid;D()[a+16>>2]=b.gid;D()[a+20>>2]=b.rdev;x[a+24>>3]=BigInt(b.size);D()[a+32>>2]=4096;D()[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();x[a+40>>3]=BigInt(Math.floor(c/1E3));E()[a+48>>2]=c%1E3*1E6;x[a+56>>3]=BigInt(Math.floor(d/1E3));E()[a+64>>2]=d%1E3*1E6;x[a+72>>3]=BigInt(Math.floor(e/1E3));E()[a+80>>2]=e%1E3*1E6;x[a+88>>3]=BigInt(b.ino);return 0}var Bd=void 0;
function tb(a,b,c){if(u)return M(3,1,a,b,c);Bd=c;try{var d=X(a);switch(b){case 0:var e=P();if(0>e)break;for(;ad[e];)e++;return re(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=P(),d.flags|=e,0;case 12:return e=P(),Ia()[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return-f.fb}}var Oe=(a,b,c)=>Nd(a,Ha(),b,c);
function ub(a,b){if(u)return M(5,1,a,b);try{if(0===b)return-28;var c=Md("/")+1;if(b<c)return-68;Oe("/",a,b);return c}catch(d){if("undefined"==typeof Z||"ErrnoError"!==d.name)throw d;return-d.fb}}
function vb(a,b,c){if(u)return M(6,1,a,b,c);Bd=c;try{var d=X(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.pb.Rb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=P();D()[e>>2]=25856;D()[e+4>>2]=5;D()[e+8>>2]=191;D()[e+12>>2]=35387;for(var f=0;32>f;f++)y()[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.pb.Sb)for(e=P(),D(),D(),D(),D(),
a=[],f=0;32>f;f++)a.push(y()[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=P();return D()[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=P();if(!d.cb.Qb)throw new R(59);return d.cb.Qb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.pb.Tb&&(f=[24,80],e=P(),Ia()[e>>1]=f[0],Ia()[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof Z||"ErrnoError"!==g.name)throw g;return-g.fb}}
function wb(a,b,c,d){if(u)return M(9,1,a,b,c,d);Bd=d;try{b=Le(b);b=Me(a,b);var e=d?P():0;return Ce(b,c,e).fd}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return-f.fb}}
function xb(a,b,c,d){if(u)return M(10,1,a,b,c,d);try{b=Le(b);d=Le(d);b=Me(a,b);d=Me(c,d);a=b;var e=Ed(a),f=Ed(d),g=Fd(a),k=Fd(d);var m=W(a,{parent:!0});var p=m.node;m=W(d,{parent:!0});var l=m.node;if(!p||!l)throw new R(44);if(p.jb!==l.jb)throw new R(75);var q=V(p,g),A=Jd(a,f);if("."!==A.charAt(0))throw new R(28);A=Jd(d,e);if("."!==A.charAt(0))throw new R(55);try{var B=V(l,k)}catch(C){}if(q!==B){var t=U(q.mode),r=oe(p,g,t);if(r)throw new R(r);if(r=B?oe(l,k,t):ne(l,k))throw new R(r);if(!p.ab.rename)throw new R(63);
if(q.qb||B&&B.qb)throw new R(10);if(l!==p&&(r=le(p,"w")))throw new R(r);Xd(q);try{p.ab.rename(q,l,k),q.parent=l}catch(C){throw C;}finally{ke(q)}}return 0}catch(C){if("undefined"==typeof Z||"ErrnoError"!==C.name)throw C;return-C.fb}}function yb(a){if(u)return M(11,1,a);try{return a=Le(a),ye(a),0}catch(b){if("undefined"==typeof Z||"ErrnoError"!==b.name)throw b;return-b.fb}}
function zb(a,b){if(u)return M(12,1,a,b);try{return a=Le(a),Ne(b,Ae(a))}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return-c.fb}}function Ab(a,b,c){if(u)return M(13,1,a,b,c);try{return b=Le(b),b=Me(a,b),0===c?ze(b):512===c?ye(b):bb("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof Z||"ErrnoError"!==d.name)throw d;return-d.fb}}
var Bb=()=>bb(""),Cb=a=>{Pa(a,!ea,1,!da,2097152,!1);Qa()},Pe=a=>{a instanceof Lc||"unwind"==a||ka(1,a)},Qe=a=>{if(!Ga&&!ya)try{if(a(),!(Ga||J||0<G))try{u?nd(za):Vb(za)}catch(b){Pe(b)}}catch(b){Pe(b)}},Ra=a=>{"function"===typeof Atomics.bc&&(Atomics.bc(D(),a>>2,a).value.then(Ta),a+=128,Atomics.store(D(),a>>2,1))},Ta=()=>{var a=hd();a&&(Ra(a),Qe(Re))},Db=(a,b)=>{a==b?setTimeout(Ta):u?postMessage({wb:a,ob:"checkMailbox"}):(a=Tc[a])&&a.postMessage({ob:"checkMailbox"})},Se=[],Eb=(a,b,c,d,e)=>{d/=2;Se.length=
d;b=e>>3;for(c=0;c<d;c++)Se[c]=x[b+2*c]?x[b+2*c+1]:Ka()[b+2*c+1];return(0,Te[a])(...Se)},Fb=()=>{J=!1;G=0},Gb=a=>{u?postMessage({ob:"cleanupThread",$b:a}):gd(Tc[a])},Hb=a=>{n&&Tc[a].ref()},Ue={},Pb=()=>performance.timeOrigin+performance.now();function Ib(a,b){if(u)return M(14,1,a,b);Ue[a]&&(clearTimeout(Ue[a].id),delete Ue[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ue[a];Qe(()=>Ve(a,performance.timeOrigin+performance.now()))},b);Ue[a]={id:c,rc:b};return 0}
var Jb=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);E()[a>>2]=60*g;D()[b>>2]=Number(f!=e);b=k=>{var m=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Oe(a,c,17),Oe(b,d,17)):(Oe(a,d,17),Oe(b,c,17))},We=1;
function Kb(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(We)a=performance.timeOrigin+performance.now();else return 52;x[c>>3]=BigInt(Math.round(1E6*a));return 0}var Mb=()=>{},Nb=()=>{G+=1;throw"unwind";};function Ob(a){if(u)return M(15,1,a);J=!1;G=0;Vb(a)}
var Qb=()=>n?require("os").cpus().length:navigator.hardwareConcurrency,Rb=a=>{var b=Ha().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-w.buffer.byteLength+65535)/65536|0;try{w.grow(d);z();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Xe={},Ze=()=>{if(!Ye){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&
navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ja||"./this.program"},b;for(b in Xe)void 0===Xe[b]?delete a[b]:a[b]=Xe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ye=c}return Ye},Ye;function Tb(a,b){if(u)return M(16,1,a,b);var c=0,d=0,e;for(e of Ze()){var f=b+c;E()[a+d>>2]=f;c+=Oe(e,f,Infinity)+1;d+=4}return 0}function Ub(a,b){if(u)return M(17,1,a,b);var c=Ze();E()[a>>2]=c.length;a=0;for(var d of c)a+=Md(d)+1;E()[b>>2]=a;return 0}
function Wb(a){if(u)return M(18,1,a);try{var b=X(a);bd(b);return 0}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return c.fb}}
function Xb(a,b,c,d){if(u)return M(19,1,a,b,c,d);try{a:{var e=X(a);a=b;for(var f,g=b=0;g<c;g++){var k=E()[a>>2],m=E()[a+4>>2];a+=8;var p=e,l=y(),q=k,A=m,B=f;if(0>A||0>B)throw new R(28);if(null===p.fd)throw new R(8);if(1===(p.flags&2097155))throw new R(8);if(U(p.node.mode))throw new R(31);if(!p.cb.read)throw new R(28);var t="undefined"!=typeof B;if(!t)B=p.position;else if(!p.seekable)throw new R(70);var r=p.cb.read(p,l,q,A,B);t||(p.position+=r);var C=r;if(0>C){var H=-1;break a}b+=C;if(C<m)break;"undefined"!=
typeof f&&(f+=C)}H=b}E()[d>>2]=H;return 0}catch(Q){if("undefined"==typeof Z||"ErrnoError"!==Q.name)throw Q;return Q.fb}}function Yb(a,b,c,d){if(u)return M(20,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=X(a);De(e,b,c);x[d>>3]=BigInt(e.position);e.zb&&0===b&&0===c&&(e.zb=null);return 0}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return f.fb}}
function Zb(a,b,c,d){if(u)return M(21,1,a,b,c,d);try{a:{var e=X(a);a=b;for(var f,g=b=0;g<c;g++){var k=E()[a>>2],m=E()[a+4>>2];a+=8;var p=Ee(e,y(),k,m,f);if(0>p){var l=-1;break a}b+=p;if(p<m)break;"undefined"!=typeof f&&(f+=p)}l=b}E()[d>>2]=l;return 0}catch(q){if("undefined"==typeof Z||"ErrnoError"!==q.name)throw q;return q.fb}}
var Jc=a=>a,$e=a=>{var b=Md(a)+1,c=Vc(b);Oe(a,c,b);return c},af=(a,b,c,d)=>{var e={string:p=>{var l=0;null!==p&&void 0!==p&&0!==p&&(l=$e(p));return l},array:p=>{var l=Vc(p.length);y().set(p,l);return l}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var m=e[c[k]];m?(0===g&&(g=K()),f[k]=m(d[k])):f[k]=d[k]}c=a(...f);return c=function(p){0!==g&&L(g);return"string"===b?Le(p):"boolean"===b?!!p:p}(c)};u||dd();ee=Array(4096);te(S,"/");Y("/tmp");Y("/home");Y("/home/web_user");
(function(){Y("/dev");Rd(259,{read:()=>0,write:(d,e,f,g)=>g,lb:()=>0});we("/dev/null",259);Qd(1280,Td);Qd(1536,Ud);we("/dev/tty",1280);we("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Hd(a),b=a.byteLength);return a[--b]};Fe("/dev","random",c);Fe("/dev","urandom",c);Y("/dev/shm");Y("/dev/shm/tmp")})();
(function(){Y("/proc");var a=Y("/proc/self");Y("/proc/self/fd");te({jb(){var b=Wd(a,"fd",16895,73);b.cb={lb:S.cb.lb};b.ab={lookup(c,d){c=+d;var e=X(c);c={parent:null,jb:{Kb:"fake"},ab:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(ad.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();S.Db=new R(44);S.Db.stack="<generic error, no stack>";
u||(h.wasmMemory?w=h.wasmMemory:w=new WebAssembly.Memory({initial:(h.INITIAL_MEMORY||16777216)/65536,maximum:32768,shared:!0}),z());h.noExitRuntime&&(J=h.noExitRuntime);h.preloadPlugins&&(Zd=h.preloadPlugins);h.print&&(va=h.print);h.printErr&&(v=h.printErr);h.wasmBinary&&(wa=h.wasmBinary);h.arguments&&(ia=h.arguments);h.thisProgram&&(ja=h.thisProgram);h.addRunDependency=$a;h.removeRunDependency=ab;
h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>af(a,b,c,f)};h.FS_createPreloadedFile=(a,b,c,d,e,f,g,k,m,p)=>{function l(B){function t(r){p?.();k||Ie(a,b,r,d,e,m);f?.();ab(A)}$d(B,q,t,()=>{g?.();ab(A)})||t(B)}var q=b?Id(Dd(a+"/"+b)):a,A=`cp ${q}`;$a(A);"string"==typeof c?Yd(c).then(l,g):l(c)};h.FS_unlink=(...a)=>ze(...a);h.FS_createPath=(...a)=>Ge(...a);h.FS_createDevice=(...a)=>Fe(...a);h.FS_createDataFile=(...a)=>Ie(...a);
h.FS_createLazyFile=(...a)=>Ke(...a);h._emscripten_force_exit=Ob;
var Te=[Kc,Yc,Ad,tb,function(a,b){if(u)return M(4,1,a,b);try{var c=X(a),d=c.node,e=c.cb.ib;a=e?c:d;e??=d.ab.ib;pe(e);var f=e(a);return Ne(b,f)}catch(g){if("undefined"==typeof Z||"ErrnoError"!==g.name)throw g;return-g.fb}},ub,vb,function(a,b){if(u)return M(7,1,a,b);try{return a=Le(a),Ne(b,Ae(a,!0))}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return-c.fb}},function(a,b,c,d){if(u)return M(8,1,a,b,c,d);try{b=Le(b);var e=d&256;b=Me(a,b,d&4096);return Ne(c,e?Ae(b,!0):Ae(b))}catch(f){if("undefined"==
typeof Z||"ErrnoError"!==f.name)throw f;return-f.fb}},wb,xb,yb,zb,Ab,Ib,Ob,Tb,Ub,Wb,Xb,Yb,Zb],ib,F=await (async function(){function a(d,e){F=d.exports;cd.push(F.Ha);md=F.Ga;xa=e;ab("wasm-instantiate");return F}$a("wasm-instantiate");var b=hb();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(u)return new Promise(d=>{La=e=>{var f=new WebAssembly.Instance(e,hb());d(a(f,e))}});cb??=h.locateFile?h.locateFile("rapfi-single.wasm",la):la+"rapfi-single.wasm";
try{var c=await gb(b);return a(c.instance,c.module)}catch(d){return ba(d),Promise.reject(d)}}());h._gomocupLoopOnce=()=>(h._gomocupLoopOnce=F.Da)();var hd=()=>(hd=F.Ea)();h._main=(a,b)=>(h._main=F.Fa)(a,b);
var bf=h.__emscripten_proxy_main=(a,b)=>(bf=h.__emscripten_proxy_main=F.Ia)(a,b),Zc=()=>(Zc=F.Ja)(),Pa=(a,b,c,d,e,f)=>(Pa=F.Ka)(a,b,c,d,e,f),Ua=()=>(Ua=F.La)(),$c=a=>($c=F.Ma)(a),Wc=(a,b,c,d,e)=>(Wc=F.Na)(a,b,c,d,e),fd=a=>(fd=F.Oa)(a),nd=a=>(nd=F.Pa)(a),Ve=(a,b)=>(Ve=F.Qa)(a,b),Re=()=>(Re=F.Ra)(),O=(a,b)=>(O=F.Sa)(a,b),xd=a=>(xd=F.Ta)(a),kd=(a,b)=>(kd=F.Ua)(a,b),L=a=>(L=F.Va)(a),Vc=a=>(Vc=F.Wa)(a),K=()=>(K=F.Xa)(),ud=a=>(ud=F.Ya)(a),rd=a=>(rd=F.Za)(a),yd=(a,b,c)=>(yd=F._a)(a,b,c),sd=a=>(sd=F.$a)(a);
function ec(a,b,c){var d=K();try{return N(a)(b,c)}catch(e){L(d);if(e!==e+0)throw e;O(1,0)}}function fc(a,b,c,d){var e=K();try{return N(a)(b,c,d)}catch(f){L(e);if(f!==f+0)throw f;O(1,0)}}function yc(a,b,c,d){var e=K();try{N(a)(b,c,d)}catch(f){L(e);if(f!==f+0)throw f;O(1,0)}}function xc(a,b,c){var d=K();try{N(a)(b,c)}catch(e){L(d);if(e!==e+0)throw e;O(1,0)}}function vc(a){var b=K();try{N(a)()}catch(c){L(b);if(c!==c+0)throw c;O(1,0)}}
function cc(a,b){var c=K();try{return N(a)(b)}catch(d){L(c);if(d!==d+0)throw d;O(1,0)}}function lc(a,b,c,d,e,f,g){var k=K();try{return N(a)(b,c,d,e,f,g)}catch(m){L(k);if(m!==m+0)throw m;O(1,0)}}function wc(a,b){var c=K();try{N(a)(b)}catch(d){L(c);if(d!==d+0)throw d;O(1,0)}}function zc(a,b,c,d,e){var f=K();try{N(a)(b,c,d,e)}catch(g){L(f);if(g!==g+0)throw g;O(1,0)}}function Ac(a,b,c,d,e,f){var g=K();try{N(a)(b,c,d,e,f)}catch(k){L(g);if(k!==k+0)throw k;O(1,0)}}
function gc(a,b,c,d,e){var f=K();try{return N(a)(b,c,d,e)}catch(g){L(f);if(g!==g+0)throw g;O(1,0)}}function Fc(a,b,c,d,e){var f=K();try{N(a)(b,c,d,e)}catch(g){L(f);if(g!==g+0)throw g;O(1,0)}}function rc(a,b,c){var d=K();try{return N(a)(b,c)}catch(e){L(d);if(e!==e+0)throw e;O(1,0)}}function dc(a,b,c){var d=K();try{return N(a)(b,c)}catch(e){L(d);if(e!==e+0)throw e;O(1,0)}}function kc(a,b,c,d,e,f){var g=K();try{return N(a)(b,c,d,e,f)}catch(k){L(g);if(k!==k+0)throw k;O(1,0)}}
function bc(a){var b=K();try{return N(a)()}catch(c){L(b);if(c!==c+0)throw c;O(1,0)}}function Hc(a,b,c,d,e){var f=K();try{N(a)(b,c,d,e)}catch(g){L(f);if(g!==g+0)throw g;O(1,0)}}function Bc(a,b,c,d,e,f,g){var k=K();try{N(a)(b,c,d,e,f,g)}catch(m){L(k);if(m!==m+0)throw m;O(1,0)}}function Ic(a,b,c){var d=K();try{N(a)(b,c)}catch(e){L(d);if(e!==e+0)throw e;O(1,0)}}function ic(a,b,c,d,e,f){var g=K();try{return N(a)(b,c,d,e,f)}catch(k){L(g);if(k!==k+0)throw k;O(1,0)}}
function jc(a,b,c,d,e,f,g){var k=K();try{return N(a)(b,c,d,e,f,g)}catch(m){L(k);if(m!==m+0)throw m;O(1,0)}}function Cc(a,b,c,d,e,f,g,k){var m=K();try{N(a)(b,c,d,e,f,g,k)}catch(p){L(m);if(p!==p+0)throw p;O(1,0)}}function Gc(a,b,c,d,e){var f=K();try{N(a)(b,c,d,e)}catch(g){L(f);if(g!==g+0)throw g;O(1,0)}}function $b(a,b){var c=K();try{return N(a)(b)}catch(d){L(c);if(d!==d+0)throw d;O(1,0)}}function tc(a,b,c){var d=K();try{return N(a)(b,c)}catch(e){L(d);if(e!==e+0)throw e;O(1,0);return 0n}}
function sc(a){var b=K();try{return N(a)()}catch(c){L(b);if(c!==c+0)throw c;O(1,0);return 0n}}function qc(a,b,c,d){var e=K();try{return N(a)(b,c,d)}catch(f){L(e);if(f!==f+0)throw f;O(1,0)}}function pc(a,b,c,d,e){var f=K();try{return N(a)(b,c,d,e)}catch(g){L(f);if(g!==g+0)throw g;O(1,0)}}function oc(a,b,c,d,e,f){var g=K();try{return N(a)(b,c,d,e,f)}catch(k){L(g);if(k!==k+0)throw k;O(1,0)}}function hc(a,b,c,d,e,f){var g=K();try{return N(a)(b,c,d,e,f)}catch(k){L(g);if(k!==k+0)throw k;O(1,0)}}
function mc(a,b,c,d,e,f,g,k){var m=K();try{return N(a)(b,c,d,e,f,g,k)}catch(p){L(m);if(p!==p+0)throw p;O(1,0)}}function nc(a,b,c,d,e,f,g,k,m,p,l,q){var A=K();try{return N(a)(b,c,d,e,f,g,k,m,p,l,q)}catch(B){L(A);if(B!==B+0)throw B;O(1,0)}}function Dc(a,b,c,d,e,f,g,k,m,p,l){var q=K();try{N(a)(b,c,d,e,f,g,k,m,p,l)}catch(A){L(q);if(A!==A+0)throw A;O(1,0)}}function Ec(a,b,c,d,e,f,g,k,m,p,l,q,A,B,t,r){var C=K();try{N(a)(b,c,d,e,f,g,k,m,p,l,q,A,B,t,r)}catch(H){L(C);if(H!==H+0)throw H;O(1,0)}}
function uc(a,b,c,d){var e=K();try{return N(a)(b,c,d)}catch(f){L(e);if(f!==f+0)throw f;O(1,0);return 0n}}function ac(a,b,c){var d=K();try{return N(a)(b,c)}catch(e){L(d);if(e!==e+0)throw e;O(1,0)}}function cf(a=[]){var b=bf;G+=1;a.unshift(ja);var c=a.length,d=Vc(4*(c+1)),e=d;a.forEach(g=>{E()[e>>2]=$e(g);e+=4});E()[e>>2]=0;try{var f=b(c,d);Vb(f,!0)}catch(g){Pe(g)}}
function df(a=ia){function b(){h.calledRun=!0;if(!ya&&(Va(),aa(h),h.onRuntimeInitialized?.(),h.noInitialRun||cf(a),!u)){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();jd.push(c)}Nc(jd)}}if(0<Ya)Za=df;else if(u)aa(h),Va();else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Oc.push(h.preRun.shift());Nc(Oc);0<Ya?Za=df:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),
1);b()},1)):b()}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();df();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Rapfi;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = Rapfi;
} else if (typeof define === 'function' && define['amd'])
  define([], () => Rapfi);
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
var isNode = typeof globalThis.process?.versions?.node == 'string';
if (isNode) isPthread = require('worker_threads').workerData === 'em-pthread'

// When running as a pthread, construct a new instance on startup
isPthread && Rapfi();
